# Generated by Django 4.0.3 on 2022-10-20 00:48

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('shoes_rest', '0002_alter_binvo_import_href'),
    ]

    operations = [
        migrations.AlterField(
            model_name='binvo',
            name='import_href',
            field=models.CharField(max_length=200, unique=True),
        ),
    ]
