# Generated by Django 4.0.3 on 2022-10-20 01:17

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('shoes_rest', '0003_alter_binvo_import_href'),
    ]

    operations = [
        migrations.RenameField(
            model_name='shoe',
            old_name='shoe_name',
            new_name='manufacturer',
        ),
        migrations.AddField(
            model_name='shoe',
            name='model_name',
            field=models.CharField(max_length=100, null=True),
        ),
    ]
